apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: az-

resources:
- ../../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: infra-common
  files:
  - ./files/common.sh

secretGenerator:
- name: infra-secret
  envs:
  - azure.env

patchesStrategicMerge:
- job-patch.yaml