apiVersion: v1
kind: Secret
metadata:
  labels:
    role: main
  name: etcd-backup-azurite
type: Opaque
data: 
  storageAccount: ZGV2c3RvcmVhY2NvdW50MQ==
  storageKey: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQ==
  # domain: YXp1cml0ZS1zZXJ2aWNlLmRlZmF1bHQ6MTAwMDA= # azurite-service.default:10000 (assuming azurite service runs in `default` namespace) # passing domain through credentials is deprecated