//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&OperatorConfiguration{}, func(obj interface{}) { SetObjectDefaults_OperatorConfiguration(obj.(*OperatorConfiguration)) })
	return nil
}

func SetObjectDefaults_OperatorConfiguration(in *OperatorConfiguration) {
	SetDefaults_ClientConnectionConfiguration(&in.ClientConnection)
	SetDefaults_LeaderElectionConfiguration(&in.LeaderElection)
	SetDefaults_ServerConfiguration(&in.Server)
	SetDefaults_EtcdControllerConfiguration(&in.Controllers.Etcd)
	SetDefaults_CompactionControllerConfiguration(&in.Controllers.Compaction)
	SetDefaults_EtcdCopyBackupsTaskControllerConfiguration(&in.Controllers.EtcdCopyBackupsTask)
	SetDefaults_SecretControllerConfiguration(&in.Controllers.Secret)
	SetDefaults_LogConfiguration(&in.LogConfiguration)
}
