---
apiVersion: v1
kind: Service
metadata:
  labels:
    gardener.cloud/role: etcd-druid
  name: etcd-druid
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    gardener.cloud/role: etcd-druid
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: webhooks
      port: 9443
      protocol: TCP
      targetPort: 9443
