apiVersion: druid.gardener.cloud/v1alpha1
kind: Etcd
metadata:
  name: etcd-test
  labels:
    app: etcd-statefulset
    gardener.cloud/role: controlplane
    role: test
spec:
  annotations:
    app: etcd-statefulset
    gardener.cloud/role: controlplane
    # networking.gardener.cloud/to-dns: allowed
    # networking.gardener.cloud/to-private-networks: allowed
    # networking.gardener.cloud/to-public-networks: allowed
    role: test
  labels:
    app: etcd-statefulset
    gardener.cloud/role: controlplane
    # networking.gardener.cloud/to-dns: allowed
    # networking.gardener.cloud/to-private-networks: allowed
    # networking.gardener.cloud/to-public-networks: allowed
    role: test
  etcd:
    metrics: basic
    defragmentationSchedule: "0 */24 * * *"
    resources:
      limits: { cpu: 500m, memory: 1Gi }
      requests: { cpu: 100m, memory: 200Mi }
    clientPort: 2379
    serverPort: 2380
    quota: 8Gi
    # heartbeatDuration: 10s
    # clientService:
    #   annotations:
    #     key: value
    #   labels:
    #     key: value
    #   trafficDistribution: PreferClose
  backup:
    port: 8080
    fullSnapshotSchedule: "0 */24 * * *"
    resources:
      limits: { cpu: 200m, memory: 1Gi }
      requests: { cpu: 23m, memory: 128Mi }
    garbageCollectionPolicy: Exponential
    garbageCollectionPeriod: 43200s
    deltaSnapshotPeriod: 300s
    deltaSnapshotMemoryLimit: 1Gi
    store:
      container: etcd-bucket
      prefix: etcd-test
      provider: S3
      endpoint: http://localstack.default:4566
      secretRef:
        name: etcd-backup-aws
    compression:
      enabled: true
      policy: "gzip"
    leaderElection:
      reelectionPeriod: 5s
      etcdConnectionTimeout: 5s

  sharedConfig:
    autoCompactionMode: periodic
    autoCompactionRetention: "30m"
  # schedulingConstraints:
    # affinity: {}
    # topologySpreadConstraints:
    # - maxSkew: 1
    #   topologyKey: topology.kubernetes.io/zone
    #   whenUnsatisfiable: DoNotSchedule
    #   labelSelector:
    #     matchLabels:
    #       app: etcd-statefulset

  replicas: 3
  # priorityClassName: priority-class-name
  # storageClass: default
  # storageCapacity: 10Gi
