apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd-druid
immutable: true
data:
{{- include "operator.config.data" . | nindent 2 }}