{{- if .Values.enabledOperatorConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-druid-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd-druid
immutable: true
data:
{{- include "operator.config.data" . | nindent 2 }}
{{- end }}
