---
apiVersion: v1
kind: Service
metadata:
  name: etcd-druid
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd-druid
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: etcd-druid
  ports:
{{- include "operator.service.ports" . | trim | nindent 4 }}
