---
apiVersion: v1
kind: Service
metadata:
  name: etcd-druid
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd-druid
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: etcd-druid
  ports:
    {{- if (((.Values.controllerManager).server).metrics).port }}
    - name: metrics
      port: {{ .Values.controllerManager.server.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.controllerManager.server.metrics.port }}
    {{- end }}
    {{- if (((.Values.controllerManager).server).webhook).port }}
    - name: webhooks
      port: {{ .Values.controllerManager.server.webhook.port }}
      protocol: TCP
      targetPort: {{ .Values.controllerManager.server.webhook.port }}
    {{- end }}
