apiVersion: batch/v1
kind: Job
metadata:
  name: infra-job
spec:
  template:
    spec:
      containers:
      - name: infra
        envFrom:
        - secretRef:
            name: infra-secret
        volumeMounts:
        - name: common
          mountPath: /var/lib/infra/data/common
      volumes:
      - name: common
        configMap:
          name: infra-common
          defaultMode: 0755
