#!/usr/bin/env bash
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eo pipefail

# For all steps, concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
else
  SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi
export SOURCE_PATH

# For the build step concourse will additionally set the following environment variable:
# BINARY_PATH - path to an existing (empty) directory to place build results into.
if [[ -z "${BINARY_PATH}" ]]; then
  BINARY_PATH="${SOURCE_PATH}/bin"
else
  BINARY_PATH="$(readlink -f "${BINARY_PATH}")/bin"
fi
export BINARY_PATH

source "${SOURCE_PATH}/.ci/common.sh"

###############################################################################

VERSION="$("${SOURCE_PATH}"/hack/get-version.sh)"
GIT_SHA="${GIT_SHA:-$(git rev-parse --short HEAD || echo "GitNotFound")}"

CGO_ENABLED=0 GO111MODULE=on go build \
  -v \
  -o "${BINARY_PATH}"/etcd-druid \
  -ldflags "-w -X ${REPOSITORY}/pkg/version.Version=${VERSION} -X ${REPOSITORY}/pkg/version.GitSHA=${GIT_SHA}" \
  main.go
