#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -eo pipefail

export SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
export BINARY_PATH="${SOURCE_PATH}/bin"

source "${SOURCE_PATH}/.ci/common.sh"

###############################################################################

VERSION="$("${SOURCE_PATH}"/hack/get-version.sh)"
GIT_SHA="${GIT_SHA:-$(git rev-parse --short HEAD || echo "GitNotFound")}"

CGO_ENABLED=0 GO111MODULE=on go build \
  -v \
  -o "${BINARY_PATH}"/etcd-druid \
  -ldflags "-w -X ${REPOSITORY}/internal/version.Version=${VERSION} -X ${REPOSITORY}/internal/version.GitSHA=${GIT_SHA}" \
  cmd/main.go
