#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

version=$(cat "$REPO_DIR"/VERSION)
sed -i "s/v[0-9]*.[0-9]*\.[0-9]*/${version}/g" "$REPO_DIR"/config/default/manager_image_patch.yaml
