#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "$0")/.."

git config --global user.email "gardener@sap.com"
git config --global user.name "Gardener CI/CD"

mkdir -p /go/src/github.com/gardener/etcd-druid
cp -r . /go/src/github.com/gardener/etcd-druid
cd /go/src/github.com/gardener/etcd-druid

make check
make check-generate
