#!/usr/bin/env bash
# Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function fetch_aws_secret() {
  CLI_PY_PATH=$1
  CC_CACHE_FILE_FLAG=$2
  echo "Fetching aws credentials from secret server..."
  export ACCESS_KEY_ID=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type aws --cfg-name etcd-backup-restore --key access_key_id`
  export SECRET_ACCESS_KEY=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type aws --cfg-name etcd-backup-restore --key secret_access_key`
  export REGION=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type aws --cfg-name etcd-backup-restore --key region`
  echo "Successfully fetched aws credentials from secret server."
}

function fetch_az_secret() {
  CLI_PY_PATH=$1
  CC_CACHE_FILE_FLAG=$2
  echo "Fetching azure credentials from secret server..."
  export STORAGE_ACCOUNT=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type azure_storage_account --cfg-name etcd-backup-restore --key storage_account_name`
  export STORAGE_KEY=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type azure_storage_account --cfg-name etcd-backup-restore --key access_key`
  echo "Successfully fetched azure credentials from secret server."
}

function fetch_gcp_secret() {
  CLI_PY_PATH=$1
  CC_CACHE_FILE_FLAG=$2
  echo "Fetching gcp credentials from secret server..."
  export SERVICEACCOUNT_JSON=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type gcp --cfg-name etcd-backup-restore --key service_account_key | tr "'" '"'`
  export PROJECT_ID=`$CLI_PY_PATH config $CC_CACHE_FILE_FLAG attribute --cfg-type gcp --cfg-name etcd-backup-restore --key project`
  echo "Successfully fetched gcp credentials from secret server."
}
