#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -eo pipefail

# For all steps, concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.
if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
else
  SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi
export SOURCE_PATH

source "${SOURCE_PATH}/.ci/common.sh"

###############################################################################

if [ -z "$COVER" ] || [ "$COVER" = false ] ; then
  echo "[INFO] Test coverage is disabled."
  make test-unit
else
  echo "[INFO] Test coverage is enabled."
  make test-cov
fi
echo "Finished executing unit tests."
