// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdCopyBackupsTaskLister helps list EtcdCopyBackupsTasks.
// All objects returned here must be treated as read-only.
type EtcdCopyBackupsTaskLister interface {
	// List lists all EtcdCopyBackupsTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdCopyBackupsTask, err error)
	// EtcdCopyBackupsTasks returns an object that can list and get EtcdCopyBackupsTasks.
	EtcdCopyBackupsTasks(namespace string) EtcdCopyBackupsTaskNamespaceLister
	EtcdCopyBackupsTaskListerExpansion
}

// etcdCopyBackupsTaskLister implements the EtcdCopyBackupsTaskLister interface.
type etcdCopyBackupsTaskLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdCopyBackupsTask]
}

// NewEtcdCopyBackupsTaskLister returns a new EtcdCopyBackupsTaskLister.
func NewEtcdCopyBackupsTaskLister(indexer cache.Indexer) EtcdCopyBackupsTaskLister {
	return &etcdCopyBackupsTaskLister{listers.New[*corev1alpha1.EtcdCopyBackupsTask](indexer, corev1alpha1.Resource("etcdcopybackupstask"))}
}

// EtcdCopyBackupsTasks returns an object that can list and get EtcdCopyBackupsTasks.
func (s *etcdCopyBackupsTaskLister) EtcdCopyBackupsTasks(namespace string) EtcdCopyBackupsTaskNamespaceLister {
	return etcdCopyBackupsTaskNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdCopyBackupsTask](s.ResourceIndexer, namespace)}
}

// EtcdCopyBackupsTaskNamespaceLister helps list and get EtcdCopyBackupsTasks.
// All objects returned here must be treated as read-only.
type EtcdCopyBackupsTaskNamespaceLister interface {
	// List lists all EtcdCopyBackupsTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdCopyBackupsTask, err error)
	// Get retrieves the EtcdCopyBackupsTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdCopyBackupsTask, error)
	EtcdCopyBackupsTaskNamespaceListerExpansion
}

// etcdCopyBackupsTaskNamespaceLister implements the EtcdCopyBackupsTaskNamespaceLister
// interface.
type etcdCopyBackupsTaskNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdCopyBackupsTask]
}
