// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdOpsTaskLister helps list EtcdOpsTasks.
// All objects returned here must be treated as read-only.
type EtcdOpsTaskLister interface {
	// List lists all EtcdOpsTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdOpsTask, err error)
	// EtcdOpsTasks returns an object that can list and get EtcdOpsTasks.
	EtcdOpsTasks(namespace string) EtcdOpsTaskNamespaceLister
	EtcdOpsTaskListerExpansion
}

// etcdOpsTaskLister implements the EtcdOpsTaskLister interface.
type etcdOpsTaskLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdOpsTask]
}

// NewEtcdOpsTaskLister returns a new EtcdOpsTaskLister.
func NewEtcdOpsTaskLister(indexer cache.Indexer) EtcdOpsTaskLister {
	return &etcdOpsTaskLister{listers.New[*corev1alpha1.EtcdOpsTask](indexer, corev1alpha1.Resource("etcdopstask"))}
}

// EtcdOpsTasks returns an object that can list and get EtcdOpsTasks.
func (s *etcdOpsTaskLister) EtcdOpsTasks(namespace string) EtcdOpsTaskNamespaceLister {
	return etcdOpsTaskNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdOpsTask](s.ResourceIndexer, namespace)}
}

// EtcdOpsTaskNamespaceLister helps list and get EtcdOpsTasks.
// All objects returned here must be treated as read-only.
type EtcdOpsTaskNamespaceLister interface {
	// List lists all EtcdOpsTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdOpsTask, err error)
	// Get retrieves the EtcdOpsTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdOpsTask, error)
	EtcdOpsTaskNamespaceListerExpansion
}

// etcdOpsTaskNamespaceLister implements the EtcdOpsTaskNamespaceLister
// interface.
type etcdOpsTaskNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdOpsTask]
}
