// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdListLister helps list EtcdLists.
// All objects returned here must be treated as read-only.
type EtcdListLister interface {
	// List lists all EtcdLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdList, err error)
	// EtcdLists returns an object that can list and get EtcdLists.
	EtcdLists(namespace string) EtcdListNamespaceLister
	EtcdListListerExpansion
}

// etcdListLister implements the EtcdListLister interface.
type etcdListLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdList]
}

// NewEtcdListLister returns a new EtcdListLister.
func NewEtcdListLister(indexer cache.Indexer) EtcdListLister {
	return &etcdListLister{listers.New[*corev1alpha1.EtcdList](indexer, corev1alpha1.Resource("etcdlist"))}
}

// EtcdLists returns an object that can list and get EtcdLists.
func (s *etcdListLister) EtcdLists(namespace string) EtcdListNamespaceLister {
	return etcdListNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdList](s.ResourceIndexer, namespace)}
}

// EtcdListNamespaceLister helps list and get EtcdLists.
// All objects returned here must be treated as read-only.
type EtcdListNamespaceLister interface {
	// List lists all EtcdLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdList, err error)
	// Get retrieves the EtcdList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdList, error)
	EtcdListNamespaceListerExpansion
}

// etcdListNamespaceLister implements the EtcdListNamespaceLister
// interface.
type etcdListNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdList]
}
