// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdCopyBackupsTaskListLister helps list EtcdCopyBackupsTaskLists.
// All objects returned here must be treated as read-only.
type EtcdCopyBackupsTaskListLister interface {
	// List lists all EtcdCopyBackupsTaskLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdCopyBackupsTaskList, err error)
	// EtcdCopyBackupsTaskLists returns an object that can list and get EtcdCopyBackupsTaskLists.
	EtcdCopyBackupsTaskLists(namespace string) EtcdCopyBackupsTaskListNamespaceLister
	EtcdCopyBackupsTaskListListerExpansion
}

// etcdCopyBackupsTaskListLister implements the EtcdCopyBackupsTaskListLister interface.
type etcdCopyBackupsTaskListLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdCopyBackupsTaskList]
}

// NewEtcdCopyBackupsTaskListLister returns a new EtcdCopyBackupsTaskListLister.
func NewEtcdCopyBackupsTaskListLister(indexer cache.Indexer) EtcdCopyBackupsTaskListLister {
	return &etcdCopyBackupsTaskListLister{listers.New[*corev1alpha1.EtcdCopyBackupsTaskList](indexer, corev1alpha1.Resource("etcdcopybackupstasklist"))}
}

// EtcdCopyBackupsTaskLists returns an object that can list and get EtcdCopyBackupsTaskLists.
func (s *etcdCopyBackupsTaskListLister) EtcdCopyBackupsTaskLists(namespace string) EtcdCopyBackupsTaskListNamespaceLister {
	return etcdCopyBackupsTaskListNamespaceLister{listers.NewNamespaced[*corev1alpha1.EtcdCopyBackupsTaskList](s.ResourceIndexer, namespace)}
}

// EtcdCopyBackupsTaskListNamespaceLister helps list and get EtcdCopyBackupsTaskLists.
// All objects returned here must be treated as read-only.
type EtcdCopyBackupsTaskListNamespaceLister interface {
	// List lists all EtcdCopyBackupsTaskLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.EtcdCopyBackupsTaskList, err error)
	// Get retrieves the EtcdCopyBackupsTaskList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.EtcdCopyBackupsTaskList, error)
	EtcdCopyBackupsTaskListNamespaceListerExpansion
}

// etcdCopyBackupsTaskListNamespaceLister implements the EtcdCopyBackupsTaskListNamespaceLister
// interface.
type etcdCopyBackupsTaskListNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.EtcdCopyBackupsTaskList]
}
