// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdLister helps list Etcds.
// All objects returned here must be treated as read-only.
type EtcdLister interface {
	// List lists all Etcds in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.Etcd, err error)
	// Etcds returns an object that can list and get Etcds.
	Etcds(namespace string) EtcdNamespaceLister
	EtcdListerExpansion
}

// etcdLister implements the EtcdLister interface.
type etcdLister struct {
	listers.ResourceIndexer[*corev1alpha1.Etcd]
}

// NewEtcdLister returns a new EtcdLister.
func NewEtcdLister(indexer cache.Indexer) EtcdLister {
	return &etcdLister{listers.New[*corev1alpha1.Etcd](indexer, corev1alpha1.Resource("etcd"))}
}

// Etcds returns an object that can list and get Etcds.
func (s *etcdLister) Etcds(namespace string) EtcdNamespaceLister {
	return etcdNamespaceLister{listers.NewNamespaced[*corev1alpha1.Etcd](s.ResourceIndexer, namespace)}
}

// EtcdNamespaceLister helps list and get Etcds.
// All objects returned here must be treated as read-only.
type EtcdNamespaceLister interface {
	// List lists all Etcds in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1alpha1.Etcd, err error)
	// Get retrieves the Etcd from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1alpha1.Etcd, error)
	EtcdNamespaceListerExpansion
}

// etcdNamespaceLister implements the EtcdNamespaceLister
// interface.
type etcdNamespaceLister struct {
	listers.ResourceIndexer[*corev1alpha1.Etcd]
}
