// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EtcdListerExpansion allows custom methods to be added to
// EtcdLister.
type EtcdListerExpansion interface{}

// EtcdNamespaceListerExpansion allows custom methods to be added to
// EtcdNamespaceLister.
type EtcdNamespaceListerExpansion interface{}

// EtcdCopyBackupsTaskListerExpansion allows custom methods to be added to
// EtcdCopyBackupsTaskLister.
type EtcdCopyBackupsTaskListerExpansion interface{}

// EtcdCopyBackupsTaskNamespaceListerExpansion allows custom methods to be added to
// EtcdCopyBackupsTaskNamespaceLister.
type EtcdCopyBackupsTaskNamespaceListerExpansion interface{}
