apiVersion: v1
kind: Secret
metadata:
  labels:
    garden.sapcloud.io/role: controlplane
    role: main
  name: etcd-backup-azurite
type: Opaque
data: 
  storageAccount: ZGV2c3RvcmVhY2NvdW50MQ==
  storageKey: RWJ5OHZkTTAyeE5PY3FGbHFVd0pQTGxtRXRsQ0RYSjFPVXpGVDUwdVNSWjZJRnN1RnEyVVZFckN6NEk2dHEvSzFTWkZQVE90ci9LQkhCZWtzb0dNR3c9PQ==
  emulatorEnabled: dHJ1ZQ== # true
  # TODO: going further, support [production-style URLs](https://github.com/Azure/Azurite?tab=readme-ov-file#production-style-url) for Azurite
  domain: YXp1cml0ZS1zZXJ2aWNlLmRlZmF1bHQ6MTAwMDA= # azurite-service.default:10000 (assuming azurite service runs in `default` namespace), emulatorEnabled has to be true
