#!/usr/bin/env bash

set -e

repo_root_dir="$1"
descriptor_out_file="${COMPONENT_DESCRIPTOR_PATH}"

echo "Enriching component descriptor from ${BASE_DEFINITION_PATH}"

image_vector_path="$repo_root_dir/internal/images/images.yaml"

# Match only images with OCM component references, ie, images created from gardener org repositories.
# In other words, don't match external images like europe-docker.pkg.dev/gardener-project/public/3rd/alpine.
component_prefixes="europe-docker.pkg.dev/gardener-project/public/gardener"

component_cli_args="
--comp-desc ${BASE_DEFINITION_PATH} \
--image-vector "$image_vector_path" \
--component-prefixes "$component_prefixes" \
"

# translates all images defined in internal/images/images.yaml into component descriptor resources.
# For detailed documentation see https://github.com/gardener/component-cli/blob/main/docs/reference/components-cli_image-vector_add.md
component-cli image-vector add $component_cli_args

cp "${BASE_DEFINITION_PATH}" "${descriptor_out_file}"
