// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package recoverfromquorumloss

import (
	"context"
	"fmt"
	"testing"
	"time"

	druidv1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	"github.com/gardener/etcd-druid/internal/client/kubernetes"
	"github.com/gardener/etcd-druid/internal/common"
	taskhandler "github.com/gardener/etcd-druid/internal/controller/etcdopstask/handler"
	druiderr "github.com/gardener/etcd-druid/internal/errors"
	"github.com/gardener/etcd-druid/test/utils"

	appsv1 "k8s.io/api/apps/v1"
	coordinationv1 "k8s.io/api/coordination/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/yaml"

	. "github.com/onsi/gomega"
)

// ---- Test helper functions ----

// buildEtcdOpsTask creates an EtcdOpsTask for the RecoverFromQuorumLoss handler with optional config.
func buildEtcdOpsTask(etcdName, namespace string, cfg *druidv1alpha1.RecoverFromQuorumLossConfig) *druidv1alpha1.EtcdOpsTask {
	return utils.EtcdOpsTaskBuilderWithDefaults("test-recover-task", namespace).
		WithEtcdName(etcdName).
		WithRecoverFromQuorumLossConfig(cfg).
		Build()
}

// createEtcd creates an Etcd resource for testing with configurable replicas, readiness, TLS, and backup store.
func createEtcd(name, namespace string, replicas int32, ready bool, withPeerTLS bool, withClientTLS bool) *druidv1alpha1.Etcd {
	eb := utils.EtcdBuilderWithoutDefaults(name, namespace).WithReplicas(replicas)
	if withPeerTLS {
		eb = eb.WithPeerTLS()
	}
	if withClientTLS {
		eb = eb.WithClientTLS()
	}
	etcd := eb.Build()
	if ready {
		etcd.Status.Ready = ptr.To(true)
		etcd.Status.Conditions = []druidv1alpha1.Condition{
			{
				Type:    druidv1alpha1.ConditionTypeReady,
				Status:  druidv1alpha1.ConditionTrue,
				Message: "etcd is ready for testing purposes",
			},
		}
	} else {
		etcd.Status.Ready = ptr.To(false)
		etcd.Status.Conditions = []druidv1alpha1.Condition{}
	}
	return etcd
}

// createEtcdWithBackup creates an Etcd resource with a local backup store configured.
func createEtcdWithBackup(name, namespace string, replicas int32, ready bool) *druidv1alpha1.Etcd {
	eb := utils.EtcdBuilderWithoutDefaults(name, namespace).WithReplicas(replicas).WithProviderLocal("test-prefix")
	etcd := eb.Build()
	if ready {
		etcd.Status.Ready = ptr.To(true)
		etcd.Status.Conditions = []druidv1alpha1.Condition{
			{
				Type:    druidv1alpha1.ConditionTypeReady,
				Status:  druidv1alpha1.ConditionTrue,
				Message: "etcd is ready for testing purposes",
			},
		}
	} else {
		etcd.Status.Ready = ptr.To(false)
		etcd.Status.Conditions = []druidv1alpha1.Condition{}
	}
	return etcd
}

// buildConfigMapWithEtcdConfig creates a ConfigMap with the etcd config YAML for the given Etcd.
// It mirrors the structure generated by internal/component/configmap/etcdconfig.go.
func buildConfigMapWithEtcdConfig(etcd *druidv1alpha1.Etcd) (*corev1.ConfigMap, error) {
	peerSvcName := druidv1alpha1.GetPeerServiceName(etcd.ObjectMeta)
	peerScheme := "http"
	if etcd.Spec.Etcd.PeerUrlTLS != nil {
		peerScheme = "https"
	}
	clientScheme := "http"
	if etcd.Spec.Etcd.ClientUrlTLS != nil {
		clientScheme = "https"
	}
	peerPort := common.DefaultPortEtcdPeer
	if etcd.Spec.Etcd.ServerPort != nil {
		peerPort = *etcd.Spec.Etcd.ServerPort
	}
	clientPort := common.DefaultPortEtcdClient
	if etcd.Spec.Etcd.ClientPort != nil {
		clientPort = *etcd.Spec.Etcd.ClientPort
	}
	initialCluster := ""
	for i := range int(etcd.Spec.Replicas) {
		podName := druidv1alpha1.GetOrdinalPodName(etcd.ObjectMeta, i)
		entry := fmt.Sprintf("%s=%s://%s.%s.%s.svc:%d",
			podName, peerScheme, podName, peerSvcName, etcd.Namespace, peerPort)
		if i > 0 {
			initialCluster += ","
		}
		initialCluster += entry
	}
	advertisePeerURLs := make(map[string][]string)
	advertiseClientURLs := make(map[string][]string)
	for i := range int(etcd.Spec.Replicas) {
		podName := druidv1alpha1.GetOrdinalPodName(etcd.ObjectMeta, i)
		advertisePeerURLs[podName] = []string{
			fmt.Sprintf("%s://%s.%s.%s.svc:%d", peerScheme, podName, peerSvcName, etcd.Namespace, peerPort),
		}
		advertiseClientURLs[podName] = []string{
			fmt.Sprintf("%s://%s.%s.%s.svc:%d", clientScheme, podName, peerSvcName, etcd.Namespace, clientPort),
		}
	}
	etcdCfg := map[string]interface{}{
		"name":                        "etcd-config",
		"initial-cluster":             initialCluster,
		"initial-cluster-state":       "new",
		"initial-advertise-peer-urls": advertisePeerURLs,
		"advertise-client-urls":       advertiseClientURLs,
		"listen-peer-urls":            fmt.Sprintf("%s://0.0.0.0:%d", peerScheme, peerPort),
		"listen-client-urls":          fmt.Sprintf("%s://0.0.0.0:%d", clientScheme, clientPort),
	}
	configBytes, err := yaml.Marshal(etcdCfg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal etcd config: %w", err)
	}
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      druidv1alpha1.GetConfigMapName(etcd.ObjectMeta),
			Namespace: etcd.Namespace,
		},
		Data: map[string]string{
			common.EtcdConfigFileName: string(configBytes),
		},
	}, nil
}

// buildStatefulSet creates a StatefulSet for the given Etcd with the specified desired and running replicas.
func buildStatefulSet(etcd *druidv1alpha1.Etcd, desiredReplicas int32, runningReplicas int32) *appsv1.StatefulSet {
	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      druidv1alpha1.GetStatefulSetName(etcd.ObjectMeta),
			Namespace: etcd.Namespace,
		},
		Spec: appsv1.StatefulSetSpec{
			Replicas: ptr.To(desiredReplicas),
		},
		Status: appsv1.StatefulSetStatus{
			Replicas:      runningReplicas,
			ReadyReplicas: runningReplicas,
		},
	}
}

// buildReadyPod creates a Pod in Running state with the Ready condition set to True.
func buildReadyPod(etcd *druidv1alpha1.Etcd) *corev1.Pod {
	return &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      druidv1alpha1.GetOrdinalPodName(etcd.ObjectMeta, 0),
			Namespace: etcd.Namespace,
		},
		Status: corev1.PodStatus{
			Phase: corev1.PodRunning,
			Conditions: []corev1.PodCondition{
				{
					Type:   corev1.PodReady,
					Status: corev1.ConditionTrue,
				},
			},
		},
	}
}

// TestRecoverFromQuorumLossAdmit tests the Admit method of the RecoverFromQuorumLoss handler.
func TestRecoverFromQuorumLossAdmit(t *testing.T) {
	g := NewGomegaWithT(t)
	tests := []struct {
		name           string
		etcdObject     *druidv1alpha1.Etcd
		expectedResult taskhandler.Result
		expectErr      bool
	}{
		{
			name:       "Should return error without requeue when Etcd object is not found",
			etcdObject: nil,
			expectedResult: taskhandler.Result{
				Description: "Etcd object not found",
				Error: &druiderr.DruidError{
					Code:      taskhandler.ErrGetEtcd,
					Operation: string(druidv1alpha1.LastOperationTypeAdmit),
					Message:   "etcd object not found",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should return error without requeue when cluster is single-member (replicas=1)",
			etcdObject: createEtcd("test-etcd", "test-ns", 1, false, false, false),
			expectedResult: taskhandler.Result{
				Description: "RecoverFromQuorumLoss task is not applicable for a single-member etcd cluster. " +
					"The backup-restore sidecar handles automatic recovery for single-member clusters.",
				Error: &druiderr.DruidError{
					Code:      ErrAdmitRecoverFromQuorumLoss,
					Operation: string(druidv1alpha1.LastOperationTypeAdmit),
					Message:   "single-member cluster does not require quorum loss recovery",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should return error without requeue when backup store is not configured",
			etcdObject: createEtcd("test-etcd", "test-ns", 3, false, false, false),
			expectedResult: taskhandler.Result{
				Description: "RecoverFromQuorumLoss requires a configured backup store. " +
					"Recovery restores etcd data from the latest snapshot; without a backup store there is nothing to restore from.",
				Error: &druiderr.DruidError{
					Code:      ErrAdmitRecoverFromQuorumLoss,
					Operation: string(druidv1alpha1.LastOperationTypeAdmit),
					Message:   "backup store is required for quorum loss recovery",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should return error without requeue when Etcd is ready (no quorum loss detected)",
			etcdObject: createEtcdWithBackup("test-etcd", "test-ns", 3, true),
			expectedResult: taskhandler.Result{
				Description: "The etcd cluster is currently ready; no quorum loss detected. " +
					"RecoverFromQuorumLoss task is only applicable when the cluster has lost quorum.",
				Error: &druiderr.DruidError{
					Code:      ErrAdmitRecoverFromQuorumLoss,
					Operation: string(druidv1alpha1.LastOperationTypeAdmit),
					Message:   "etcd cluster is ready; quorum loss not detected",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should pass admit check when cluster is multi-member, has backup, and has quorum loss",
			etcdObject: createEtcdWithBackup("test-etcd", "test-ns", 3, false),
			expectedResult: taskhandler.Result{
				Description: "Preconditions for RecoverFromQuorumLoss task are satisfied",
				Requeue:     false,
			},
			expectErr: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.etcdObject != nil {
				objs = append(objs, tc.etcdObject)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask("test-etcd", "test-ns", nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())

			admitResult := taskHandler.Admit(context.Background())
			g.Expect(admitResult.Requeue).To(Equal(tc.expectedResult.Requeue))
			g.Expect(admitResult.Description).To(Equal(tc.expectedResult.Description))

			if tc.expectErr {
				g.Expect(admitResult.Error).ToNot(BeNil())
				if expectedDruidErr, ok := tc.expectedResult.Error.(*druiderr.DruidError); ok {
					g.Expect(admitResult.Error).To(BeAssignableToTypeOf(&druiderr.DruidError{}))
					druidErr := admitResult.Error.(*druiderr.DruidError)
					g.Expect(druidErr.Code).To(Equal(expectedDruidErr.Code))
					g.Expect(druidErr.Operation).To(Equal(expectedDruidErr.Operation))
					g.Expect(druidErr.Message).To(Equal(expectedDruidErr.Message))
				}
			} else {
				g.Expect(admitResult.Error).To(BeNil())
			}
		})
	}
}

// TestRecoverFromQuorumLossCleanup tests the Cleanup method of the RecoverFromQuorumLoss handler.
func TestRecoverFromQuorumLossCleanup(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)
	tests := []struct {
		name                string
		etcdObject          *druidv1alpha1.Etcd
		expectedDescription string
	}{
		{
			name:                "Should skip cleanup when Etcd is not found",
			etcdObject:          nil,
			expectedDescription: "Etcd object not found during cleanup; skipping annotation removal",
		},
		{
			name:                "Should be a no-op when recovery annotations are absent",
			etcdObject:          createEtcd(etcdName, namespace, 3, false, false, false),
			expectedDescription: "No cleanup required for RecoverFromQuorumLoss task",
		},
		{
			name: "Should remove all recovery annotations including step annotation",
			etcdObject: func() *druidv1alpha1.Etcd {
				etcd := createEtcd(etcdName, namespace, 3, false, false, false)
				etcd.Annotations = map[string]string{
					druidv1alpha1.SuspendEtcdSpecReconcileAnnotation:       "true",
					druidv1alpha1.DisableEtcdComponentProtectionAnnotation: "true",
					recoveryStepAnnotation:                                 string(stepScaleDown),
				}
				return etcd
			}(),
			expectedDescription: "Cleanup completed: recovery annotations removed from Etcd resource",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.etcdObject != nil {
				objs = append(objs, tc.etcdObject)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())

			cleanupResult := taskHandler.Cleanup(context.Background())
			g.Expect(cleanupResult.Requeue).To(BeFalse())
			g.Expect(cleanupResult.Description).To(Equal(tc.expectedDescription))
			g.Expect(cleanupResult.Error).To(BeNil())

			if tc.etcdObject != nil && tc.expectedDescription == "Cleanup completed: recovery annotations removed from Etcd resource" {
				updated := &druidv1alpha1.Etcd{}
				g.Expect(cl.Get(context.Background(), types.NamespacedName{Name: etcdName, Namespace: namespace}, updated)).To(Succeed())
				g.Expect(updated.Annotations).ToNot(HaveKey(druidv1alpha1.SuspendEtcdSpecReconcileAnnotation))
				g.Expect(updated.Annotations).ToNot(HaveKey(druidv1alpha1.DisableEtcdComponentProtectionAnnotation))
				g.Expect(updated.Annotations).ToNot(HaveKey(recoveryStepAnnotation))
			}
		})
	}
}

// runUntilDone drives Execute in a loop, simulating the reconciler's requeue behaviour.
// It stops when Requeue is false (success or terminal error) and returns the final result.
// maxIter guards against infinite loops in tests.
func runUntilDone(ctx context.Context, h taskhandler.Handler, maxIter int) taskhandler.Result {
	var result taskhandler.Result
	for range maxIter {
		result = h.Execute(ctx)
		if !result.Requeue {
			return result
		}
	}
	return result
}

// TestRecoverFromQuorumLossExecute tests the Execute method through the full requeue loop.
func TestRecoverFromQuorumLossExecute(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	tests := []struct {
		name           string
		etcdObject     *druidv1alpha1.Etcd
		extraObjects   func(etcd *druidv1alpha1.Etcd) []client.Object
		expectedResult taskhandler.Result
		expectErr      bool
	}{
		{
			name:       "Should return error when Etcd object is not found",
			etcdObject: nil,
			expectedResult: taskhandler.Result{
				Description: "Etcd object not found",
				Error: &druiderr.DruidError{
					Code:      taskhandler.ErrGetEtcd,
					Operation: string(druidv1alpha1.LastOperationTypeExecution),
					Message:   "etcd object not found",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should requeue while StatefulSet is still scaling down",
			etcdObject: createEtcd(etcdName, namespace, 3, false, false, false),
			extraObjects: func(etcd *druidv1alpha1.Etcd) []client.Object {
				return []client.Object{buildStatefulSet(etcd, 3, 3)}
			},
			expectedResult: taskhandler.Result{
				Description: "Waiting for StatefulSet to scale down to 0 replicas",
				Requeue:     true,
			},
			expectErr: false,
		},
		{
			name:       "Should fail when ConfigMap is absent after scale-down",
			etcdObject: createEtcd(etcdName, namespace, 3, false, false, false),
			extraObjects: func(etcd *druidv1alpha1.Etcd) []client.Object {
				return []client.Object{buildStatefulSet(etcd, 0, 0)}
			},
			expectedResult: taskhandler.Result{
				Description: "Failed during step PatchConfigMap",
				Error: &druiderr.DruidError{
					Code:      ErrExecuteRecoverFromQuorumLoss,
					Operation: string(druidv1alpha1.LastOperationTypeExecution),
					Message:   "failed to execute step PatchConfigMap",
				},
				Requeue: false,
			},
			expectErr: true,
		},
		{
			name:       "Should requeue while pod is not yet ready",
			etcdObject: createEtcd(etcdName, namespace, 3, false, false, false),
			extraObjects: func(etcd *druidv1alpha1.Etcd) []client.Object {
				cm, _ := buildConfigMapWithEtcdConfig(etcd)
				return []client.Object{buildStatefulSet(etcd, 0, 0), cm}
			},
			expectedResult: taskhandler.Result{
				Description: "Waiting for single-member etcd pod to become ready",
				Requeue:     true,
			},
			expectErr: false,
		},
		{
			name:       "Should complete recovery successfully",
			etcdObject: createEtcd(etcdName, namespace, 3, false, false, false),
			extraObjects: func(etcd *druidv1alpha1.Etcd) []client.Object {
				cm, _ := buildConfigMapWithEtcdConfig(etcd)
				return []client.Object{buildStatefulSet(etcd, 0, 0), cm, buildReadyPod(etcd)}
			},
			expectedResult: taskhandler.Result{
				Description: "Recovery from quorum loss completed successfully. " +
					"etcd-druid will reconcile and bring up the remaining cluster members.",
				Requeue: false,
			},
			expectErr: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.etcdObject != nil {
				objs = append(objs, tc.etcdObject)
			}
			if tc.extraObjects != nil && tc.etcdObject != nil {
				objs = append(objs, tc.extraObjects(tc.etcdObject)...)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())

			result := runUntilDone(context.Background(), taskHandler, 30)
			g.Expect(result.Requeue).To(Equal(tc.expectedResult.Requeue))
			g.Expect(result.Description).To(Equal(tc.expectedResult.Description))

			if tc.expectErr {
				g.Expect(result.Error).ToNot(BeNil())
				if expectedDruidErr, ok := tc.expectedResult.Error.(*druiderr.DruidError); ok {
					g.Expect(result.Error).To(BeAssignableToTypeOf(&druiderr.DruidError{}))
					druidErr := result.Error.(*druiderr.DruidError)
					g.Expect(druidErr.Code).To(Equal(expectedDruidErr.Code))
					g.Expect(druidErr.Operation).To(Equal(expectedDruidErr.Operation))
					g.Expect(druidErr.Message).To(Equal(expectedDruidErr.Message))
				}
			} else {
				g.Expect(result.Error).To(BeNil())
			}
		})
	}
}

// TestRecoverFromQuorumLossExecuteStepByStep verifies that each reconcile call advances
// exactly one step, records the step annotation on the Etcd CR, and that resuming Execute
// from an annotated state skips already-completed steps.
func TestRecoverFromQuorumLossExecuteStepByStep(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	etcd := createEtcdWithBackup(etcdName, namespace, 3, false)
	cm, err := buildConfigMapWithEtcdConfig(etcd)
	g.Expect(err).To(BeNil())
	sts := buildStatefulSet(etcd, 3, 3)
	pod := buildReadyPod(etcd)

	cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).
		WithObjects(etcd, cm, sts, pod).Build()
	task := buildEtcdOpsTask(etcdName, namespace, nil)
	taskHandler, handlerErr := New(cl, task, nil)
	g.Expect(handlerErr).To(BeNil())

	ctx := context.Background()

	type stepExpect struct {
		step        recoveryStep
		description string
		// sideEffect is called after Execute() returns for this step, before the next Execute().
		// Use it to simulate external state changes that the fake client won't do automatically.
		sideEffect func()
	}
	// Each entry represents one reconcile invocation that should succeed and requeue.
	// sideEffect functions simulate controller-managed status changes the fake client won't do.
	expectations := []stepExpect{
		{step: stepSuspendReconciliation, description: "Suspended etcd-druid reconciliation"},
		{step: stepDisableComponentProtect, description: "Disabled etcd component protection"},
		{step: stepScaleDown, description: "Scaled StatefulSet down to 0 replicas", sideEffect: func() {
			// Simulate the StatefulSet controller driving replicas to 0 in status.
			sts := &appsv1.StatefulSet{}
			g.Expect(cl.Get(ctx, types.NamespacedName{Name: etcdName, Namespace: namespace}, sts)).To(Succeed())
			sts.Status.Replicas = 0
			sts.Status.ReadyReplicas = 0
			g.Expect(cl.Status().Update(ctx, sts)).To(Succeed())
		}},
		{step: stepWaitScaleDown, description: "StatefulSet scaled down to 0 replicas"},
		{step: stepDeletePVCs, description: "Deleted all PVCs"},
		{step: stepDeleteMemberLeases, description: "Deleted all member leases"},
		{step: stepPatchConfigMap, description: "Patched ConfigMap to single-member configuration"},
		{step: stepScaleUp, description: "Scaled StatefulSet up to 1 replica"},
		{step: stepWaitPodReady, description: "Single-member etcd pod is ready"},
		{step: stepReenableReconciliation, description: "Re-enabled etcd-druid reconciliation"},
	}

	for _, exp := range expectations {
		result := taskHandler.Execute(ctx)
		g.Expect(result.Error).To(BeNil(), "unexpected error at step %s", exp.step)
		g.Expect(result.Requeue).To(BeTrue(), "expected requeue after step %s", exp.step)
		g.Expect(result.Description).To(Equal(exp.description), "wrong description at step %s", exp.step)

		updatedEtcd := &druidv1alpha1.Etcd{}
		g.Expect(cl.Get(ctx, types.NamespacedName{Name: etcdName, Namespace: namespace}, updatedEtcd)).To(Succeed())
		g.Expect(updatedEtcd.Annotations).To(HaveKeyWithValue(recoveryStepAnnotation, string(exp.step)),
			"step annotation not recorded after step %s", exp.step)

		if exp.sideEffect != nil {
			exp.sideEffect()
		}
	}

	// Final step returns success with no requeue.
	result := taskHandler.Execute(ctx)
	g.Expect(result.Error).To(BeNil())
	g.Expect(result.Requeue).To(BeFalse())
	g.Expect(result.Description).To(Equal("Recovery from quorum loss completed successfully. " +
		"etcd-druid will reconcile and bring up the remaining cluster members."))
}

// TestUpdateConfigMapForSingleMember tests the updateConfigMapForSingleMember method.
func TestUpdateConfigMapForSingleMember(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "etcd-main"
		namespace = "test-ns"
	)

	tests := []struct {
		name           string
		replicas       int32
		withPeerTLS    bool
		withClientTLS  bool
		skipConfigMap  bool
		missingDataKey bool
		expectErr      bool
	}{
		{
			name:      "Should update ConfigMap to single member for 3-member cluster without TLS",
			replicas:  3,
			expectErr: false,
		},
		{
			name:          "Should update ConfigMap using https scheme for 3-member cluster with peer+client TLS",
			replicas:      3,
			withPeerTLS:   true,
			withClientTLS: true,
			expectErr:     false,
		},
		{
			name:          "Should return error when ConfigMap does not exist",
			replicas:      3,
			skipConfigMap: true,
			expectErr:     true,
		},
		{
			name:           "Should return error when ConfigMap is missing the etcd config key",
			replicas:       3,
			missingDataKey: true,
			expectErr:      true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			eb := utils.EtcdBuilderWithoutDefaults(etcdName, namespace).WithReplicas(tc.replicas)
			if tc.withPeerTLS {
				eb = eb.WithPeerTLS()
			}
			if tc.withClientTLS {
				eb = eb.WithClientTLS()
			}
			etcd := eb.Build()

			objs := []client.Object{etcd}
			if !tc.skipConfigMap {
				var cm *corev1.ConfigMap
				if tc.missingDataKey {
					// ConfigMap exists but is missing the etcd config key
					cm = &corev1.ConfigMap{
						ObjectMeta: metav1.ObjectMeta{
							Name:      druidv1alpha1.GetConfigMapName(etcd.ObjectMeta),
							Namespace: namespace,
						},
						Data: map[string]string{"other-key": "other-value"},
					}
				} else {
					var err error
					cm, err = buildConfigMapWithEtcdConfig(etcd)
					g.Expect(err).To(BeNil())
				}
				objs = append(objs, cm)
			}

			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())

			updateErr := taskHandler.(*Handler).updateConfigMapForSingleMember(context.Background(), etcd)
			if tc.expectErr {
				g.Expect(updateErr).ToNot(BeNil())
				return
			}
			g.Expect(updateErr).To(BeNil())

			updatedCM := &corev1.ConfigMap{}
			g.Expect(cl.Get(context.Background(), types.NamespacedName{
				Name:      druidv1alpha1.GetConfigMapName(etcd.ObjectMeta),
				Namespace: namespace,
			}, updatedCM)).To(Succeed())

			configData := updatedCM.Data[common.EtcdConfigFileName]
			g.Expect(configData).ToNot(BeEmpty())

			var etcdConfig map[string]interface{}
			g.Expect(yaml.Unmarshal([]byte(configData), &etcdConfig)).To(Succeed())

			peerScheme := "http"
			if tc.withPeerTLS {
				peerScheme = "https"
			}
			clientScheme := "http"
			if tc.withClientTLS {
				clientScheme = "https"
			}
			peerSvcName := druidv1alpha1.GetPeerServiceName(etcd.ObjectMeta)
			member0 := druidv1alpha1.GetOrdinalPodName(etcd.ObjectMeta, 0)
			expectedPeerURL := fmt.Sprintf("%s://%s.%s.%s.svc:%d",
				peerScheme, member0, peerSvcName, namespace, common.DefaultPortEtcdPeer)
			expectedClientURL := fmt.Sprintf("%s://%s.%s.%s.svc:%d",
				clientScheme, member0, peerSvcName, namespace, common.DefaultPortEtcdClient)

			g.Expect(etcdConfig["initial-cluster"]).To(Equal(fmt.Sprintf("%s=%s", member0, expectedPeerURL)))
			g.Expect(etcdConfig["initial-cluster-state"]).To(Equal("new"))

			advertisePeerRaw, ok := etcdConfig["initial-advertise-peer-urls"]
			g.Expect(ok).To(BeTrue(), "initial-advertise-peer-urls should be present")
			advertisePeerMap, ok := advertisePeerRaw.(map[string]interface{})
			g.Expect(ok).To(BeTrue())
			g.Expect(advertisePeerMap).To(HaveLen(1))
			g.Expect(advertisePeerMap).To(HaveKey(member0))
			peerURLs, _ := advertisePeerMap[member0].([]interface{})
			g.Expect(peerURLs).To(HaveLen(1))
			g.Expect(peerURLs[0]).To(Equal(expectedPeerURL))

			advertiseClientRaw, ok := etcdConfig["advertise-client-urls"]
			g.Expect(ok).To(BeTrue(), "advertise-client-urls should be present")
			advertiseClientMap, ok := advertiseClientRaw.(map[string]interface{})
			g.Expect(ok).To(BeTrue())
			g.Expect(advertiseClientMap).To(HaveLen(1))
			g.Expect(advertiseClientMap).To(HaveKey(member0))
			clientURLs, _ := advertiseClientMap[member0].([]interface{})
			g.Expect(clientURLs).To(HaveLen(1))
			g.Expect(clientURLs[0]).To(Equal(expectedClientURL))
		})
	}
}

// TestIsStsScaledDown tests the isStsScaledDown helper.
func TestIsStsScaledDown(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "etcd-main"
		namespace = "test-ns"
	)
	etcd := utils.EtcdBuilderWithoutDefaults(etcdName, namespace).WithReplicas(3).Build()

	tests := []struct {
		name               string
		statefulSet        *appsv1.StatefulSet
		expectedScaledDown bool
	}{
		{
			name:               "StatefulSet not found: should be considered scaled down",
			statefulSet:        nil,
			expectedScaledDown: true,
		},
		{
			name:               "StatefulSet has 3 running replicas: should not be scaled down",
			statefulSet:        buildStatefulSet(etcd, 3, 3),
			expectedScaledDown: false,
		},
		{
			name:               "StatefulSet has 0 running replicas: should be considered scaled down",
			statefulSet:        buildStatefulSet(etcd, 0, 0),
			expectedScaledDown: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.statefulSet != nil {
				objs = append(objs, tc.statefulSet)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())

			stsKey := types.NamespacedName{
				Name:      druidv1alpha1.GetStatefulSetName(etcd.ObjectMeta),
				Namespace: namespace,
			}
			scaledDown, checkErr := taskHandler.(*Handler).isStsScaledDown(context.Background(), stsKey)
			g.Expect(checkErr).To(BeNil())
			g.Expect(scaledDown).To(Equal(tc.expectedScaledDown))
		})
	}
}

// TestNewHandlerTimeoutConfig tests that New() correctly reads timeout values from the task config.
func TestNewHandlerTimeoutConfig(t *testing.T) {
	g := NewGomegaWithT(t)
	cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).Build()

	tests := []struct {
		name                     string
		cfg                      *druidv1alpha1.RecoverFromQuorumLossConfig
		expectedScaleDownTimeout float64
		expectedPodReadyTimeout  float64
	}{
		{
			name:                     "Should use default timeouts when config is nil",
			cfg:                      nil,
			expectedScaleDownTimeout: defaultScaleDownTimeout.Seconds(),
			expectedPodReadyTimeout:  defaultPodReadyTimeout.Seconds(),
		},
		{
			name: "Should use custom timeouts from config",
			cfg: &druidv1alpha1.RecoverFromQuorumLossConfig{
				ScaleDownTimeout: &metav1.Duration{Duration: 60 * time.Second},
				PodReadyTimeout:  &metav1.Duration{Duration: 120 * time.Second},
			},
			expectedScaleDownTimeout: 60,
			expectedPodReadyTimeout:  120,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			task := buildEtcdOpsTask("e", "ns", tc.cfg)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			h := taskHandler.(*Handler)
			g.Expect(h.scaleDownTimeout.Seconds()).To(Equal(tc.expectedScaleDownTimeout))
			g.Expect(h.podReadyTimeout.Seconds()).To(Equal(tc.expectedPodReadyTimeout))
		})
	}
}

// TestHelperFunctions tests the serverPortOrDefault and clientPortOrDefault helpers.
func TestHelperFunctions(t *testing.T) {
	g := NewGomegaWithT(t)

	tests := []struct {
		name           string
		setServerPort  *int32
		setClientPort  *int32
		expectedServer int32
		expectedClient int32
	}{
		{
			name:           "Should return default peer port when ServerPort is nil",
			expectedServer: common.DefaultPortEtcdPeer,
			expectedClient: common.DefaultPortEtcdClient,
		},
		{
			name:           "Should return configured ports when both are set",
			setServerPort:  ptr.To(int32(3380)),
			setClientPort:  ptr.To(int32(3379)),
			expectedServer: 3380,
			expectedClient: 3379,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			etcd := utils.EtcdBuilderWithoutDefaults("e", "ns").Build()
			etcd.Spec.Etcd.ServerPort = tc.setServerPort
			etcd.Spec.Etcd.ClientPort = tc.setClientPort
			g.Expect(serverPortOrDefault(etcd)).To(Equal(tc.expectedServer))
			g.Expect(clientPortOrDefault(etcd)).To(Equal(tc.expectedClient))
		})
	}
}

// TestDeleteAllPVCs tests the deleteAllPVCs method including the delete-iteration path.
func TestDeleteAllPVCs(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)
	etcd := createEtcd(etcdName, namespace, 3, false, false, false)

	tests := []struct {
		name string
		pvcs []*corev1.PersistentVolumeClaim
	}{
		{
			name: "Should succeed when no PVCs exist",
		},
		{
			name: "Should delete all matching PVCs",
			pvcs: []*corev1.PersistentVolumeClaim{
				{
					ObjectMeta: metav1.ObjectMeta{
						Name:      "etcd-data-test-etcd-0",
						Namespace: namespace,
						Labels: map[string]string{
							"app.kubernetes.io/managed-by": "etcd-druid",
							"app.kubernetes.io/part-of":    etcdName,
						},
					},
				},
			},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			objs = append(objs, etcd)
			for _, pvc := range tc.pvcs {
				objs = append(objs, pvc)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			delErr := taskHandler.(*Handler).deleteAllPVCs(context.Background(), etcd)
			g.Expect(delErr).To(BeNil())
		})
	}
}

// TestDeleteAllMemberLeases tests the deleteAllMemberLeases method including the delete-iteration path.
func TestDeleteAllMemberLeases(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)
	etcd := createEtcd(etcdName, namespace, 3, false, false, false)

	tests := []struct {
		name   string
		leases []*coordinationv1.Lease
	}{
		{
			name: "Should succeed when no member leases exist",
		},
		{
			name: "Should delete all matching member leases",
			leases: []*coordinationv1.Lease{
				{
					ObjectMeta: metav1.ObjectMeta{
						Name:      etcdName + "-0",
						Namespace: namespace,
						Labels: map[string]string{
							druidv1alpha1.LabelComponentKey: common.ComponentNameMemberLease,
							"app.kubernetes.io/part-of":     etcdName,
						},
					},
				},
			},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			objs = append(objs, etcd)
			for _, lease := range tc.leases {
				objs = append(objs, lease)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			delErr := taskHandler.(*Handler).deleteAllMemberLeases(context.Background(), etcd)
			g.Expect(delErr).To(BeNil())
		})
	}
}

// TestIsPodReady tests the isPodReady method covering all pod states.
func TestIsPodReady(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)
	etcd := createEtcd(etcdName, namespace, 3, false, false, false)
	podKey := types.NamespacedName{
		Name:      druidv1alpha1.GetOrdinalPodName(etcd.ObjectMeta, 0),
		Namespace: namespace,
	}

	tests := []struct {
		name          string
		pod           *corev1.Pod
		expectedReady bool
	}{
		{
			name:          "Pod not found: should return not ready",
			pod:           nil,
			expectedReady: false,
		},
		{
			name: "Pod in Pending phase: should return not ready",
			pod: &corev1.Pod{
				ObjectMeta: metav1.ObjectMeta{Name: podKey.Name, Namespace: namespace},
				Status:     corev1.PodStatus{Phase: corev1.PodPending},
			},
			expectedReady: false,
		},
		{
			name: "Pod Running but no Ready condition: should return not ready",
			pod: &corev1.Pod{
				ObjectMeta: metav1.ObjectMeta{Name: podKey.Name, Namespace: namespace},
				Status:     corev1.PodStatus{Phase: corev1.PodRunning, Conditions: []corev1.PodCondition{}},
			},
			expectedReady: false,
		},
		{
			name: "Pod Running with Ready=False: should return not ready",
			pod: &corev1.Pod{
				ObjectMeta: metav1.ObjectMeta{Name: podKey.Name, Namespace: namespace},
				Status: corev1.PodStatus{
					Phase: corev1.PodRunning,
					Conditions: []corev1.PodCondition{
						{Type: corev1.PodReady, Status: corev1.ConditionFalse},
					},
				},
			},
			expectedReady: false,
		},
		{
			name:          "Pod Running with Ready=True: should return ready",
			pod:           buildReadyPod(etcd),
			expectedReady: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.pod != nil {
				objs = append(objs, tc.pod)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			ready, checkErr := taskHandler.(*Handler).isPodReady(context.Background(), podKey)
			g.Expect(checkErr).To(BeNil())
			g.Expect(ready).To(Equal(tc.expectedReady))
		})
	}
}

// TestSuspendReconciliation tests the suspendReconciliation method.
func TestSuspendReconciliation(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	tests := []struct {
		name        string
		annotations map[string]string
	}{
		{
			name: "Should add suspend annotation when missing",
		},
		{
			name: "Should be a no-op when suspend annotation is already present",
			annotations: map[string]string{
				druidv1alpha1.SuspendEtcdSpecReconcileAnnotation: "true",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			etcd := createEtcd(etcdName, namespace, 3, false, false, false)
			if tc.annotations != nil {
				etcd.Annotations = tc.annotations
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(etcd).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			g.Expect(taskHandler.(*Handler).suspendReconciliation(context.Background(), etcd)).To(Succeed())
			updated := &druidv1alpha1.Etcd{}
			g.Expect(cl.Get(context.Background(), types.NamespacedName{Name: etcdName, Namespace: namespace}, updated)).To(Succeed())
			g.Expect(updated.Annotations).To(HaveKey(druidv1alpha1.SuspendEtcdSpecReconcileAnnotation))
		})
	}
}

// TestDisableComponentProtection tests the disableComponentProtection method.
func TestDisableComponentProtection(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	tests := []struct {
		name        string
		annotations map[string]string
	}{
		{
			name: "Should add disable-protection annotation when missing",
		},
		{
			name: "Should be a no-op when disable-protection annotation is already present",
			annotations: map[string]string{
				druidv1alpha1.DisableEtcdComponentProtectionAnnotation: "true",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			etcd := createEtcd(etcdName, namespace, 3, false, false, false)
			if tc.annotations != nil {
				etcd.Annotations = tc.annotations
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(etcd).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			g.Expect(taskHandler.(*Handler).disableComponentProtection(context.Background(), etcd)).To(Succeed())
			updated := &druidv1alpha1.Etcd{}
			g.Expect(cl.Get(context.Background(), types.NamespacedName{Name: etcdName, Namespace: namespace}, updated)).To(Succeed())
			g.Expect(updated.Annotations).To(HaveKey(druidv1alpha1.DisableEtcdComponentProtectionAnnotation))
		})
	}
}

// TestEnableComponentProtection tests the enableComponentProtection method.
func TestEnableComponentProtection(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	tests := []struct {
		name                   string
		annotations            map[string]string
		expectAnnotationAbsent bool
	}{
		{
			name:                   "Should be a no-op when disable-protection annotation is not present",
			annotations:            nil,
			expectAnnotationAbsent: true,
		},
		{
			name: "Should remove the annotation when it is present",
			annotations: map[string]string{
				druidv1alpha1.DisableEtcdComponentProtectionAnnotation: "true",
			},
			expectAnnotationAbsent: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			etcd := createEtcd(etcdName, namespace, 3, false, false, false)
			if tc.annotations != nil {
				etcd.Annotations = tc.annotations
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(etcd).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			protErr := taskHandler.(*Handler).enableComponentProtection(context.Background(), etcd)
			g.Expect(protErr).To(BeNil())
			updated := &druidv1alpha1.Etcd{}
			g.Expect(cl.Get(context.Background(), types.NamespacedName{Name: etcdName, Namespace: namespace}, updated)).To(Succeed())
			g.Expect(updated.Annotations).ToNot(HaveKey(druidv1alpha1.DisableEtcdComponentProtectionAnnotation))
		})
	}
}

// TestScaleStatefulSetTo tests the scaleStatefulSetTo helper covering the idempotent case.
func TestScaleStatefulSetTo(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)
	etcd := createEtcd(etcdName, namespace, 3, false, false, false)

	tests := []struct {
		name            string
		statefulSet     *appsv1.StatefulSet
		desiredReplicas int32
	}{
		{
			name:            "STS not found: should be a no-op",
			statefulSet:     nil,
			desiredReplicas: 0,
		},
		{
			name:            "STS already at desired replicas: should be a no-op",
			statefulSet:     buildStatefulSet(etcd, 0, 0),
			desiredReplicas: 0,
		},
		{
			name:            "STS needs scaling: should update replicas",
			statefulSet:     buildStatefulSet(etcd, 3, 3),
			desiredReplicas: 0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var objs []client.Object
			if tc.statefulSet != nil {
				objs = append(objs, tc.statefulSet)
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			scaleErr := taskHandler.(*Handler).scaleStatefulSetTo(context.Background(), etcd, tc.desiredReplicas)
			g.Expect(scaleErr).To(BeNil())
		})
	}
}

// TestEnableReconciliation tests the enableReconciliation method.
func TestEnableReconciliation(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	tests := []struct {
		name        string
		annotations map[string]string
	}{
		{
			name: "Should add reconcile annotation when etcd has no annotations",
		},
		{
			name: "Should remove suspend annotation and add reconcile annotation",
			annotations: map[string]string{
				druidv1alpha1.SuspendEtcdSpecReconcileAnnotation: "true",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			etcd := createEtcd(etcdName, namespace, 3, false, false, false)
			if tc.annotations != nil {
				etcd.Annotations = tc.annotations
			}
			cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(etcd).Build()
			task := buildEtcdOpsTask(etcdName, namespace, nil)
			taskHandler, err := New(cl, task, nil)
			g.Expect(err).To(BeNil())
			recErr := taskHandler.(*Handler).enableReconciliation(context.Background(), etcd)
			g.Expect(recErr).To(BeNil())
			updated := &druidv1alpha1.Etcd{}
			g.Expect(cl.Get(context.Background(), types.NamespacedName{Name: etcdName, Namespace: namespace}, updated)).To(Succeed())
			g.Expect(updated.Annotations).ToNot(HaveKey(druidv1alpha1.SuspendEtcdSpecReconcileAnnotation))
			g.Expect(updated.Annotations).To(HaveKeyWithValue(druidv1alpha1.DruidOperationAnnotation, druidv1alpha1.DruidOperationReconcile))
		})
	}
}

// TestRecoverFromQuorumLossExecuteWithPVCsAndLeases tests Execute when PVCs and leases exist.
// This exercises the deletion iteration paths in deleteAllPVCs and deleteAllMemberLeases.
func TestRecoverFromQuorumLossExecuteWithPVCsAndLeases(t *testing.T) {
	g := NewGomegaWithT(t)
	const (
		etcdName  = "test-etcd"
		namespace = "test-ns"
	)

	etcd := createEtcdWithBackup(etcdName, namespace, 3, false)
	cm, err := buildConfigMapWithEtcdConfig(etcd)
	g.Expect(err).To(BeNil())

	// Pre-create STS at 0, a matching PVC, a matching lease, ConfigMap, and a ready pod.
	pvc := &corev1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "etcd-data-test-etcd-0",
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/managed-by": "etcd-druid",
				"app.kubernetes.io/part-of":    etcdName,
			},
		},
	}
	lease := &coordinationv1.Lease{
		ObjectMeta: metav1.ObjectMeta{
			Name:      etcdName + "-0",
			Namespace: namespace,
			Labels: map[string]string{
				druidv1alpha1.LabelComponentKey: common.ComponentNameMemberLease,
				"app.kubernetes.io/part-of":     etcdName,
			},
		},
	}

	objs := []client.Object{etcd, cm, buildStatefulSet(etcd, 0, 0), buildReadyPod(etcd), pvc, lease}
	cl := utils.NewTestClientBuilder().WithScheme(kubernetes.Scheme).WithObjects(objs...).Build()

	task := buildEtcdOpsTask(etcdName, namespace, &druidv1alpha1.RecoverFromQuorumLossConfig{
		ScaleDownTimeout: &metav1.Duration{Duration: time.Second},
		PodReadyTimeout:  &metav1.Duration{Duration: time.Second},
	})
	taskHandler, err := New(cl, task, nil)
	g.Expect(err).To(BeNil())

	t.Run("Should complete recovery and delete PVCs and leases", func(_ *testing.T) {
		result := runUntilDone(context.Background(), taskHandler, 30)
		g.Expect(result.Error).To(BeNil())
		g.Expect(result.Requeue).To(BeFalse())
		g.Expect(result.Description).To(Equal("Recovery from quorum loss completed successfully. " +
			"etcd-druid will reconcile and bring up the remaining cluster members."))

		// Verify PVC and lease were deleted.
		pvcList := &corev1.PersistentVolumeClaimList{}
		g.Expect(cl.List(context.Background(), pvcList, client.InNamespace(namespace))).To(Succeed())
		g.Expect(pvcList.Items).To(BeEmpty())

		leaseList := &coordinationv1.LeaseList{}
		g.Expect(cl.List(context.Background(), leaseList, client.InNamespace(namespace))).To(Succeed())
		g.Expect(leaseList.Items).To(BeEmpty())
	})
}
