// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	corev1alpha1 "github.com/gardener/etcd-druid/client/clientset/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEtcdCopyBackupsTaskLists implements EtcdCopyBackupsTaskListInterface
type fakeEtcdCopyBackupsTaskLists struct {
	*gentype.FakeClientWithList[*v1alpha1.EtcdCopyBackupsTaskList, *v1alpha1.EtcdCopyBackupsTaskListList]
	Fake *FakeDruidV1alpha1
}

func newFakeEtcdCopyBackupsTaskLists(fake *FakeDruidV1alpha1, namespace string) corev1alpha1.EtcdCopyBackupsTaskListInterface {
	return &fakeEtcdCopyBackupsTaskLists{
		gentype.NewFakeClientWithList[*v1alpha1.EtcdCopyBackupsTaskList, *v1alpha1.EtcdCopyBackupsTaskListList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("etcdcopybackupstasklists"),
			v1alpha1.SchemeGroupVersion.WithKind("EtcdCopyBackupsTaskList"),
			func() *v1alpha1.EtcdCopyBackupsTaskList { return &v1alpha1.EtcdCopyBackupsTaskList{} },
			func() *v1alpha1.EtcdCopyBackupsTaskListList { return &v1alpha1.EtcdCopyBackupsTaskListList{} },
			func(dst, src *v1alpha1.EtcdCopyBackupsTaskListList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EtcdCopyBackupsTaskListList) []*v1alpha1.EtcdCopyBackupsTaskList {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.EtcdCopyBackupsTaskListList, items []*v1alpha1.EtcdCopyBackupsTaskList) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
