// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	corev1alpha1 "github.com/gardener/etcd-druid/client/clientset/versioned/typed/core/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEtcds implements EtcdInterface
type fakeEtcds struct {
	*gentype.FakeClientWithList[*v1alpha1.Etcd, *v1alpha1.EtcdList]
	Fake *FakeDruidV1alpha1
}

func newFakeEtcds(fake *FakeDruidV1alpha1, namespace string) corev1alpha1.EtcdInterface {
	return &fakeEtcds{
		gentype.NewFakeClientWithList[*v1alpha1.Etcd, *v1alpha1.EtcdList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("etcds"),
			v1alpha1.SchemeGroupVersion.WithKind("Etcd"),
			func() *v1alpha1.Etcd { return &v1alpha1.Etcd{} },
			func() *v1alpha1.EtcdList { return &v1alpha1.EtcdList{} },
			func(dst, src *v1alpha1.EtcdList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EtcdList) []*v1alpha1.Etcd { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EtcdList, items []*v1alpha1.Etcd) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
