apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/owned-by: "{{ .Release.Namespace }}/{{ .Values.ownerName }}"
    gardener.cloud/owner-type: "etcdcopybackupstask"
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  ownerReferences:
  - apiVersion: druid.gardener.cloud/v1alpha1
    kind: EtcdCopyBackupsTask
    name: {{ .Values.ownerName }}
    uid: {{ .Values.ownerUID }}
    controller: true
    blockOwnerDeletion: true
spec:
  template:
    metadata:
      labels:
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
    spec:
      restartPolicy: OnFailure
      containers:
      - name: copy-backups
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        command:
        - etcdbrctl
        - copy
        - --snapstore-temp-directory=/var/etcd/data/tmp
{{- if .Values.targetStore.storageProvider }}
        - --storage-provider={{ .Values.targetStore.storageProvider }}
{{- end }}
{{- if .Values.targetStore.storePrefix }}
        - --store-prefix={{ .Values.targetStore.storePrefix }}
{{- end }}
{{- if .Values.targetStore.storageContainer }}
        - --store-container={{ .Values.targetStore.storageContainer }}
{{- end }}
{{- if .Values.sourceStore.storageProvider }}
        - --source-storage-provider={{ .Values.sourceStore.storageProvider }}
{{- end }}
{{- if .Values.sourceStore.storePrefix }}
        - --source-store-prefix={{ .Values.sourceStore.storePrefix }}
{{- end }}
{{- if .Values.sourceStore.storageContainer }}
        - --source-store-container={{ .Values.sourceStore.storageContainer }}
{{- end }}
{{- if .Values.maxBackupAge }}
        - --max-backup-age={{ .Values.maxBackupAge }}
{{- end }}
{{- if .Values.maxBackups }}
        - --max-backups-to-copy={{ .Values.maxBackups }}
{{- end }}
{{- if .Values.waitForFinalSnapshot }}
        - --wait-for-final-snapshot={{ .Values.waitForFinalSnapshot }}
{{- if .Values.waitForFinalSnapshotTimeout }}
        - --wait-for-final-snapshot-timeout={{ .Values.waitForFinalSnapshotTimeout }}
{{- end }}
{{- end }}
        env:
{{- if .Values.targetStore.storageContainer }}
        - name: STORAGE_CONTAINER
          value: {{ .Values.targetStore.storageContainer }}
{{- end }}
{{- if .Values.sourceStore.storageContainer }}
        - name: SOURCE_STORAGE_CONTAINER
          value: {{ .Values.sourceStore.storageContainer }}
{{- end }}
{{- if eq .Values.targetStore.storageProvider "S3" }}
        - name: "AWS_REGION"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "region"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "secretAccessKey"
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "accessKeyID"
{{- else if eq .Values.targetStore.storageProvider "ABS" }}
        - name: "STORAGE_ACCOUNT"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "storageAccount"
        - name: "STORAGE_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "storageKey"
{{- else if eq .Values.targetStore.storageProvider "GCS" }}
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/root/.gcp/serviceaccount.json"
{{- else if eq .Values.targetStore.storageProvider "Swift" }}
        - name: "OS_AUTH_URL"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "authURL"
        - name: "OS_DOMAIN_NAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "domainName"
        - name: "OS_USERNAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "username"
        - name: "OS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "password"
        - name: "OS_TENANT_NAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "tenantName"
{{- else if eq .Values.targetStore.storageProvider "OSS" }}
        - name: "ALICLOUD_ENDPOINT"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "storageEndpoint"
        - name: "ALICLOUD_ACCESS_KEY_SECRET"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "accessKeySecret"
        - name: "ALICLOUD_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.targetStore.storeSecret }}
              key: "accessKeyID"
{{- end }}
{{- if eq .Values.sourceStore.storageProvider "S3" }}
        - name: "SOURCE_AWS_REGION"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "region"
        - name: "SOURCE_AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "secretAccessKey"
        - name: "SOURCE_AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "accessKeyID"
{{- else if eq .Values.sourceStore.storageProvider "ABS" }}
        - name: "SOURCE_STORAGE_ACCOUNT"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "storageAccount"
        - name: "SOURCE_STORAGE_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "storageKey"
{{- else if eq .Values.sourceStore.storageProvider "GCS" }}
        - name: SOURCE_GOOGLE_APPLICATION_CREDENTIALS
          value: "/root/.source-gcp/serviceaccount.json"
{{- else if eq .Values.sourceStore.storageProvider "Swift" }}
        - name: "SOURCE_OS_AUTH_URL"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "authURL"
        - name: "SOURCE_OS_DOMAIN_NAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "domainName"
        - name: "SOURCE_OS_USERNAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "username"
        - name: "SOURCE_OS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "password"
        - name: "SOURCE_OS_TENANT_NAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "tenantName"
{{- else if eq .Values.sourceStore.storageProvider "OSS" }}
        - name: "SOURCE_ALICLOUD_ENDPOINT"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "storageEndpoint"
        - name: "SOURCE_ALICLOUD_ACCESS_KEY_SECRET"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "accessKeySecret"
        - name: "SOURCE_ALICLOUD_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sourceStore.storeSecret }}
              key: "accessKeyID"
{{- end }}
{{- if or (eq .Values.targetStore.storageProvider "GCS") (eq .Values.sourceStore.storageProvider "GCS") }}
        volumeMounts:
{{- if eq .Values.targetStore.storageProvider "GCS" }}
        - name: etcd-backup
          mountPath: "/root/.gcp/"
{{- end }}
{{- if eq .Values.sourceStore.storageProvider "GCS" }}
        - name: source-etcd-backup
          mountPath: "/root/.source-gcp/"
{{- end }}
      volumes:
{{- if eq .Values.targetStore.storageProvider "GCS" }}
      - name: etcd-backup
        secret:
          secretName: {{ .Values.targetStore.storeSecret }}
{{- end }}
{{- if eq .Values.sourceStore.storageProvider "GCS" }}
      - name: source-etcd-backup
        secret:
          secretName: {{ .Values.sourceStore.storeSecret }}
{{- end }}
{{- end }}