// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	scheme "github.com/gardener/etcd-druid/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdCopyBackupsTaskListsGetter has a method to return a EtcdCopyBackupsTaskListInterface.
// A group's client should implement this interface.
type EtcdCopyBackupsTaskListsGetter interface {
	EtcdCopyBackupsTaskLists(namespace string) EtcdCopyBackupsTaskListInterface
}

// EtcdCopyBackupsTaskListInterface has methods to work with EtcdCopyBackupsTaskList resources.
type EtcdCopyBackupsTaskListInterface interface {
	Create(ctx context.Context, etcdCopyBackupsTaskList *corev1alpha1.EtcdCopyBackupsTaskList, opts v1.CreateOptions) (*corev1alpha1.EtcdCopyBackupsTaskList, error)
	Update(ctx context.Context, etcdCopyBackupsTaskList *corev1alpha1.EtcdCopyBackupsTaskList, opts v1.UpdateOptions) (*corev1alpha1.EtcdCopyBackupsTaskList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.EtcdCopyBackupsTaskList, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.EtcdCopyBackupsTaskListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.EtcdCopyBackupsTaskList, err error)
	EtcdCopyBackupsTaskListExpansion
}

// etcdCopyBackupsTaskLists implements EtcdCopyBackupsTaskListInterface
type etcdCopyBackupsTaskLists struct {
	*gentype.ClientWithList[*corev1alpha1.EtcdCopyBackupsTaskList, *corev1alpha1.EtcdCopyBackupsTaskListList]
}

// newEtcdCopyBackupsTaskLists returns a EtcdCopyBackupsTaskLists
func newEtcdCopyBackupsTaskLists(c *DruidV1alpha1Client, namespace string) *etcdCopyBackupsTaskLists {
	return &etcdCopyBackupsTaskLists{
		gentype.NewClientWithList[*corev1alpha1.EtcdCopyBackupsTaskList, *corev1alpha1.EtcdCopyBackupsTaskListList](
			"etcdcopybackupstasklists",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.EtcdCopyBackupsTaskList { return &corev1alpha1.EtcdCopyBackupsTaskList{} },
			func() *corev1alpha1.EtcdCopyBackupsTaskListList { return &corev1alpha1.EtcdCopyBackupsTaskListList{} },
		),
	}
}
