// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	scheme "github.com/gardener/etcd-druid/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdOpsTasksGetter has a method to return a EtcdOpsTaskInterface.
// A group's client should implement this interface.
type EtcdOpsTasksGetter interface {
	EtcdOpsTasks(namespace string) EtcdOpsTaskInterface
}

// EtcdOpsTaskInterface has methods to work with EtcdOpsTask resources.
type EtcdOpsTaskInterface interface {
	Create(ctx context.Context, etcdOpsTask *corev1alpha1.EtcdOpsTask, opts v1.CreateOptions) (*corev1alpha1.EtcdOpsTask, error)
	Update(ctx context.Context, etcdOpsTask *corev1alpha1.EtcdOpsTask, opts v1.UpdateOptions) (*corev1alpha1.EtcdOpsTask, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcdOpsTask *corev1alpha1.EtcdOpsTask, opts v1.UpdateOptions) (*corev1alpha1.EtcdOpsTask, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.EtcdOpsTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.EtcdOpsTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.EtcdOpsTask, err error)
	EtcdOpsTaskExpansion
}

// etcdOpsTasks implements EtcdOpsTaskInterface
type etcdOpsTasks struct {
	*gentype.ClientWithList[*corev1alpha1.EtcdOpsTask, *corev1alpha1.EtcdOpsTaskList]
}

// newEtcdOpsTasks returns a EtcdOpsTasks
func newEtcdOpsTasks(c *DruidV1alpha1Client, namespace string) *etcdOpsTasks {
	return &etcdOpsTasks{
		gentype.NewClientWithList[*corev1alpha1.EtcdOpsTask, *corev1alpha1.EtcdOpsTaskList](
			"etcdopstasks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.EtcdOpsTask { return &corev1alpha1.EtcdOpsTask{} },
			func() *corev1alpha1.EtcdOpsTaskList { return &corev1alpha1.EtcdOpsTaskList{} },
		),
	}
}
