// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/gardener/etcd-druid/api/core/v1alpha1"
	scheme "github.com/gardener/etcd-druid/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdsGetter has a method to return a EtcdInterface.
// A group's client should implement this interface.
type EtcdsGetter interface {
	Etcds(namespace string) EtcdInterface
}

// EtcdInterface has methods to work with Etcd resources.
type EtcdInterface interface {
	Create(ctx context.Context, etcd *corev1alpha1.Etcd, opts v1.CreateOptions) (*corev1alpha1.Etcd, error)
	Update(ctx context.Context, etcd *corev1alpha1.Etcd, opts v1.UpdateOptions) (*corev1alpha1.Etcd, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcd *corev1alpha1.Etcd, opts v1.UpdateOptions) (*corev1alpha1.Etcd, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.Etcd, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.EtcdList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.Etcd, err error)
	EtcdExpansion
}

// etcds implements EtcdInterface
type etcds struct {
	*gentype.ClientWithList[*corev1alpha1.Etcd, *corev1alpha1.EtcdList]
}

// newEtcds returns a Etcds
func newEtcds(c *DruidV1alpha1Client, namespace string) *etcds {
	return &etcds{
		gentype.NewClientWithList[*corev1alpha1.Etcd, *corev1alpha1.EtcdList](
			"etcds",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corev1alpha1.Etcd { return &corev1alpha1.Etcd{} },
			func() *corev1alpha1.EtcdList { return &corev1alpha1.EtcdList{} },
		),
	}
}
