// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type EtcdExpansion interface{}

type EtcdCopyBackupsTaskExpansion interface{}

type EtcdOpsTaskExpansion interface{}
